### ISSUE TITLE
Sua badge do Alura Challenge está aqui!

### ISSUE THREAD

**Issue by LucasdeFreitasp** [JJBarata/aluraflix-backend#1]
Olá, backender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nesse primeiro Challenge de Back-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅
.
Abraços e te vejo nos próximos Challenges!
![Badge AluraFlix reduzido - Sharer](https://user-images.githubusercontent.com/79534537/130669184-b625b874-9f73-4757-9b3b-804588cf95d7.png)

**Comment by JJBarata** [comment]
Obrigado!
